stages:
    - deploy

variables:
    PACKAGE_REGISTRY_PROJECT: gitlab.com/api/v4/projects/27157125/packages
    MRWATTS_PRIVATE_PACKAGE_REGISTRY_USERNAME: gitlab-ci-token
    MRWATTS_PRIVATE_PACKAGE_REGISTRY_PASSWORD: ${CI_JOB_TOKEN}

Dotnet Package Registry Publication:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    stage: deploy
    script:
        - dotnet build -c Release
        - dotnet nuget push "bin/Release/*.nupkg" --source mrwatts-private-package-registry
    only:
        - tags